/**
 * Developer inspection page for actual prompts and policy sources used by each agent.
 *
 * Author: Sarala Biswal
 */
import { Braces, Code2, Copy, FileCode2, GitBranch, ScrollText, ShieldCheck } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import {
  getDeveloperPrompts,
  getRevenueControls,
  getRevenueOpportunities,
  type DeveloperPromptPreview,
  type RevenueControls,
  type RevenueOpportunity,
} from "../api/client";
import { EmptyState, SectionHeader, SkeletonLoader, StatusBadge } from "../components";

export function DeveloperCorner() {
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [opportunities, setOpportunities] = useState<RevenueOpportunity[]>([]);
  const [controls, setControls] = useState<RevenueControls | null>(null);
  const [preview, setPreview] = useState<DeveloperPromptPreview | null>(null);
  const [selectedOpportunityId, setSelectedOpportunityId] = useState("RCC-OPP-002");
  const [selectedPromptVersion, setSelectedPromptVersion] = useState("v2.2");
  const [guardrailsEnabled, setGuardrailsEnabled] = useState(true);
  const [activePromptName, setActivePromptName] = useState("context");
  const guardrailApplies = selectedPromptVersion === "v2.2";
  const effectiveGuardrailsEnabled = guardrailApplies && guardrailsEnabled;

  useEffect(() => {
    let cancelled = false;
    Promise.all([getRevenueOpportunities(), getRevenueControls()])
      .then(([nextOpportunities, nextControls]) => {
        if (cancelled) return;
        setOpportunities(nextOpportunities);
        setControls(nextControls);
        setSelectedOpportunityId((current) => (
          nextOpportunities.some((item) => item.opportunity_id === current)
            ? current
            : nextOpportunities[0]?.opportunity_id ?? current
        ));
      })
      .catch(() => {
        if (cancelled) return;
        setOpportunities([]);
        setControls(null);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!selectedOpportunityId) return;
    let cancelled = false;
    setRefreshing(true);
    getDeveloperPrompts({
      opportunityId: selectedOpportunityId,
      promptVersion: selectedPromptVersion,
      approvalGuardrailsEnabled: effectiveGuardrailsEnabled,
    })
      .then((nextPreview) => {
        if (cancelled) return;
        setPreview(nextPreview);
        setActivePromptName((current) => (
          nextPreview.prompts.some((item) => item.prompt_name === current)
            ? current
            : nextPreview.prompts[0]?.prompt_name ?? current
        ));
      })
      .catch(() => {
        if (!cancelled) setPreview(null);
      })
      .finally(() => {
        if (!cancelled) setRefreshing(false);
      });
    return () => {
      cancelled = true;
    };
  }, [effectiveGuardrailsEnabled, selectedOpportunityId, selectedPromptVersion]);

  const activePrompt = useMemo(
    () => preview?.prompts.find((item) => item.prompt_name === activePromptName) ?? preview?.prompts[0] ?? null,
    [activePromptName, preview],
  );

  if (loading) {
    return <SkeletonLoader rows={8} />;
  }

  if (!opportunities.length || !controls || !preview || !activePrompt) {
    return (
      <EmptyState
        icon={Code2}
        title="Developer prompt preview is not connected"
        sub="Start the API to inspect the actual Quote-to-Cash agent prompts."
        action="Refresh"
        onAction={() => window.location.reload()}
      />
    );
  }

  return (
    <>
      <SectionHeader
        eyebrow="Developer Corner"
        title="Actual prompts behind the Quote-to-Cash agents"
        sub="Inspect the prompt text generated by the same backend prompt builder used by the running agent flow."
      />

      <section className="developer-toolbar">
        <label className="field-label">
          Opportunity
          <select
            className="select-input"
            value={selectedOpportunityId}
            onChange={(event) => setSelectedOpportunityId(event.target.value)}
          >
            {opportunities.map((item) => (
              <option key={item.opportunity_id} value={item.opportunity_id}>
                {item.account.name} - {item.name}
              </option>
            ))}
          </select>
        </label>
        <label className="field-label">
          Prompt version
          <select
            className="select-input"
            value={selectedPromptVersion}
            onChange={(event) => setSelectedPromptVersion(event.target.value)}
          >
            {controls.prompt_versions.map((item) => (
              <option key={item.value} value={item.value}>
                {item.label}
              </option>
            ))}
          </select>
        </label>
        <label className={`developer-toggle ${guardrailApplies ? "" : "developer-toggle-disabled"}`}>
          <input
            checked={effectiveGuardrailsEnabled}
            onChange={(event) => setGuardrailsEnabled(event.target.checked)}
            disabled={!guardrailApplies}
            type="checkbox"
          />
          <span>{guardrailApplies ? "Enforce approval policy" : "Approval policy requires v2.2"}</span>
        </label>
        <span className="live-chip">{refreshing ? "Refreshing prompts" : "Prompt preview live"}</span>
      </section>

      <section className="developer-summary-grid">
        <DeveloperSummary icon={GitBranch} label="Prompt family" value={preview.prompt_version} detail={preview.opportunity_name} />
        <DeveloperSummary icon={ShieldCheck} label="Guardrails" value={preview.approval_guardrails_enabled ? "Enforced" : "Advisory"} detail="approval routing mode" />
        <DeveloperSummary icon={Braces} label="Agent prompts" value={preview.prompts.length.toString()} detail="one call per agent step" />
      </section>

      <div className="developer-layout">
        <aside className="developer-agent-list" aria-label="Quote-to-Cash agent prompts">
          {preview.prompts.map((prompt) => (
            <button
              className={`developer-agent-button ${prompt.prompt_name === activePrompt.prompt_name ? "developer-agent-button-active" : ""}`}
              key={prompt.prompt_name}
              onClick={() => setActivePromptName(prompt.prompt_name)}
              type="button"
            >
              <FileCode2 size={16} aria-hidden="true" />
              <span>{prompt.agent_name}</span>
              <strong>Prompt contract: {prompt.prompt_contract}</strong>
            </button>
          ))}
        </aside>

        <section className="developer-prompt-panel">
          <div className="developer-prompt-head">
            <div>
              <p className="detail-kicker">{activePrompt.system}</p>
              <h3>{activePrompt.agent_name}</h3>
              <span>{activePrompt.label}</span>
            </div>
            <button
              className="icon-button"
              onClick={() => void navigator.clipboard?.writeText(activePrompt.prompt)}
              title="Copy prompt"
              type="button"
            >
              <Copy size={16} aria-hidden="true" />
            </button>
          </div>
          <div className="developer-contract-grid">
            <article className="developer-contract-card">
              <div className="developer-contract-head">
                <FileCode2 size={16} aria-hidden="true" />
                <div>
                  <p className="detail-kicker">Actual LLM prompt</p>
                  <h4>{activePrompt.prompt_contract}</h4>
                </div>
              </div>
              <pre className="developer-prompt-code">{activePrompt.prompt}</pre>
            </article>
            <article className="developer-contract-card">
              <div className="developer-contract-head">
                <ScrollText size={16} aria-hidden="true" />
                <div>
                  <p className="detail-kicker">Policy source</p>
                  <h4>{activePrompt.policy_source.title}</h4>
                </div>
              </div>
              <div className="developer-policy-source">
                <dl>
                  <div>
                    <dt>Policy ID</dt>
                    <dd>{activePrompt.policy_source.policy_id}</dd>
                  </div>
                  <div>
                    <dt>Owner</dt>
                    <dd>{activePrompt.policy_source.owner}</dd>
                  </div>
                  <div>
                    <dt>Version</dt>
                    <dd>{activePrompt.policy_source.version}</dd>
                  </div>
                  <div>
                    <dt>Source</dt>
                    <dd>{activePrompt.policy_source.source}</dd>
                  </div>
                </dl>
                <ul>
                  {activePrompt.policy_source.rules.map((rule) => (
                    <li key={rule}>{rule}</li>
                  ))}
                </ul>
              </div>
            </article>
          </div>
          <div className="developer-observability">
            <p className="detail-kicker">Telemetry captured when this prompt runs</p>
            <div>
              {activePrompt.observability_fields.map((field) => (
                <StatusBadge key={field} status={field} />
              ))}
            </div>
          </div>
        </section>
      </div>
    </>
  );
}

function DeveloperSummary({
  icon: Icon,
  label,
  value,
  detail,
}: {
  icon: LucideIcon;
  label: string;
  value: string;
  detail: string;
}) {
  return (
    <article className="developer-summary-card">
      <Icon size={18} aria-hidden="true" />
      <span>{label}</span>
      <strong>{value}</strong>
      <p>{detail}</p>
    </article>
  );
}
